//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagCloudGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagCloudGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///the
        ///and
        ///for
        ///it
        ///it&apos;s
        ///they
        ///them
        ///those
        ///this
        ///these
        ///that
        ///theirs
        ///i
        ///not
        ///he
        ///she
        ///him
        ///her
        ///his
        ///hers
        ///as
        ///but
        ///or
        ///an
        ///will
        ///my
        ///all
        ///would
        ///there
        ///their
        ///to
        ///of
        ///in
        ///on
        ///with
        ///at
        ///by
        ///from
        ///into
        ///me
        ///if
        ///is
        ///have
        ///had
        ///do
        ///be
        ///am
        ///are
        ///no
        ///one
        ///only
        ///out
        ///said
        ///so
        ///some
        ///up
        ///upon
        ///was
        ///very
        ///were
        ///what
        ///which
        ///who
        ///you
        ///your
        ///about
        ///after
        ///any
        ///been
        ///before
        ///being
        ///come
        ///came
        ///did
        ///even
        ///ever
        ///every
        ///like
        ///how
        ///must
        ///now
        ///our
        ///we
        ///own
        ///s
        ///t
        ///ll
        ///while
        ///yet
        ///where
        ///thing
        ///then
        ///than
        ///say
        ///
        ///could        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonWords {
            get {
                return ResourceManager.GetString("CommonWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    font-family:                   &apos;Raleway&apos;, sans-seriff;
        ///    background:                    silver;
        ///    color:                         #455672; 
        ///}
        ///
        ///.content {
        ///    background:                    #fffff0;
        ///    width:                         85%;
        ///    margin:                        auto;
        ///    margin-top:                    50px;
        ///    margin-bottom:                 75px;
        ///    height:                        100%;
        ///    border:                        4px solid gray;
        ///    padding:                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css_template {
            get {
                return ResourceManager.GetString("css_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;/div&gt;
        ///        &lt;!-- --------------------------Footer------------------------------ --&gt;
        ///            &lt;section class=&quot;divider&quot; id=&quot;footerDivider&quot;&gt;&lt;/section&gt;
        ///            &lt;p class=&quot;footerNotes&quot;&gt;Website generated by Matthew Shoemaker&lt;/p&gt;
        ///        &lt;!-- --------------------------Footer------------------------------ --&gt;           
        ///        &lt;/div&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt; .
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Tag Cloud Generator&lt;/title&gt;
        ///        &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;tagcloud.css&quot;&gt;
        ///        &lt;link href=&quot;https://fonts.googleapis.com/css?family=Raleway&quot;rel=&quot;stylesheet&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt; 
        ///        &lt;div class=&quot;content&quot;&gt;
        ///**Insert Title**
        ///            &lt;section class=&quot;divider&quot;&gt;&lt;/section&gt;
        ///            
        ///            &lt;div&gt;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
    }
}
